"""2.3s business sign-off is durable and actually filters (SPEC-2).

The signoff layer used to be structurally dead: the only writer was a local-only
frontend edit, and the reader looked at the `a-business-validation` artifact body
— which no code path persisted and which 2.3 rewrites on every run. So an
explicit "no" could never reject anything, while the funnel still credited the
layer for indicators nobody had reviewed.

Run: PYTHONPATH=. .venv/bin/python -m app.agents._test_ledger_signoff
"""
from __future__ import annotations

from app.agents.ledger import drops_before, signoff_reject_l3
from app.domain.models import ArtifactInstance, IndustryRef, ProjectMeta
from app.store.state import initial_state


def _state():
    return initial_state(ProjectMeta(
        id="signoff-test", name="T", brand="B",
        industry=IndustryRef(l1="food-bev", l2="beverage", l3="sports-functional"),
        kpi="Vol", createdAt="2026-01-01T00:00:00+00:00"))


def test_only_an_explicit_no_rejects() -> None:
    st = _state()
    assert signoff_reject_l3(st) == set(), "a fresh project rejects nothing"

    st.signoffs = {"TV": "yes", "Promotion": "no", "Display": ""}
    assert signoff_reject_l3(st) == {"promotion"}, signoff_reject_l3(st)


def test_verdict_is_not_read_from_the_artifact_body() -> None:
    """A verdict in the artifact body is decoration; only state counts.

    This is the regression: the body is regenerated by 2.3 on every run, so
    trusting it meant trusting something that is erased on the next step.
    """
    st = _state()
    st.artifacts.append(ArtifactInstance(
        id="a-business-validation", name="BV", taskRef="2.3", type="report", stage="s2",
        format="validation", body={"groups": [{"l3": "TV", "signoff": "no"}]},
        version=1, state="confirmed", producedByAgent="data", producedAtTick=0))
    assert signoff_reject_l3(st) == set(), "the body must not drive the ledger"

    st.signoffs = {"TV": "no"}
    assert signoff_reject_l3(st) == {"tv"}


def test_a_rejected_factor_is_inherited_downstream() -> None:
    """A rejected L3 is dropped for every layer after signoff — the whole point
    of the layer. `drops_before` is what each later layer asks."""
    st = _state()
    st.signoffs = {"Promotion": "no"}

    # Nothing has been scored, so the drop set is driven purely by the L3
    # rejection reaching the layers that come after it.
    before_signoff = drops_before(st, "signoff")
    after_signoff = drops_before(st, "statistical")
    assert len(after_signoff) >= len(before_signoff)


def test_signoffs_serialize_snake_case() -> None:
    """ProjectState's own fields carry no alias — an aliased key here would be
    emitted as camelCase and silently missed by the frontend's reader."""
    st = _state()
    st.signoffs = {"TV": "no"}
    dumped = st.model_dump(by_alias=True)
    assert "signoffs" in dumped and dumped["signoffs"] == {"TV": "no"}


if __name__ == "__main__":
    test_only_an_explicit_no_rejects()
    test_verdict_is_not_read_from_the_artifact_body()
    test_a_rejected_factor_is_inherited_downstream()
    test_signoffs_serialize_snake_case()
    print("signoff ledger tests passed")
